---
name: The Drop Bears
description: FRC Team 4774 from Sydney, Australia - Building robots, inspiring students, and advancing STEM education
author: The Drop Bears
url: https://thedropbears.org.au
ogImage: /static/img/team-og-image.jpg
