name: "The Drop Bears"
description: "FRC Team 4774 from Sydney, Australia"
siteUrl: "https://thedropbears.org.au"
defaultOgImage: "/static/img/og-default.jpg"
banner:
  enabled: true
  text: "Our interest form is now open!"
  linkText: "Express your interest"
  url: "/eoi/"
social:
  youtube: "https://www.youtube.com/@thedropbears"
  instagram: "https://www.instagram.com/frc_thedropbears"
  github: "https://www.github.com/thedropbears"
  email: "enquiries@thedropbears.org.au"
